/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./utils/**/*.{js,ts,jsx,tsx}",
  ],
  plugins: [require("daisyui")],
  darkTheme: "gingersDarkTheme",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        gingersLightTheme: {
          primary: "#D9480F",
          "primary-content": "#FFFFFF",
          secondary: "#E25822",
          "secondary-content": "#1E1E1E",
          accent: "#FFDAB9",
          "accent-content": "#1E1E1E",
          neutral: "#FAF3E0",
          "neutral-content": "#1E1E1E",
          "base-100": "#FFF7F0",
          "base-200": "#FFEBD6",
          "base-300": "#FFDAB9",
          "base-content": "#1E1E1E",
          info: "#E25822",
          success: "#D9480F",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        gingersDarkTheme: {
          primary: "#D9480F",
          "primary-content": "#FFFFFF",
          secondary: "#E25822",
          "secondary-content": "#FAF3E0",
          accent: "#FFDAB9",
          "accent-content": "#1E1E1E",
          neutral: "#FAF3E0",
          "neutral-content": "#1E1E1E",
          "base-100": "#FFDAB9",
          "base-200": "#FAF3E0",
          "base-300": "#FFDAB9",
          "base-content": "#1E1E1E",
          info: "#E25822",
          success: "#D9480F",
          warning: "#FFDAB9",
          error: "#E25822",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "hsl(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        legacyLight: {
          primary: "#C8F5FF",
          "primary-content": "#026262",
          secondary: "#89d7e9",
          "secondary-content": "#088484",
          accent: "#026262",
          "accent-content": "#E9FBFF",
          neutral: "#088484",
          "neutral-content": "#F0FCFF",
          "base-100": "#F0FCFF",
          "base-200": "#E1FAFF",
          "base-300": "#C8F5FF",
          "base-content": "#088484",
          info: "#026262",
          success: "#34EEB6",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        legacyDark: {
          primary: "#026262",
          "primary-content": "#C8F5FF",
          secondary: "#107575",
          "secondary-content": "#E9FBFF",
          accent: "#C8F5FF",
          "accent-content": "#088484",
          neutral: "#E9FBFF",
          "neutral-content": "#11ACAC",
          "base-100": "#11ACAC",
          "base-200": "#088484",
          "base-300": "#026262",
          "base-content": "#E9FBFF",
          info: "#C8F5FF",
          success: "#34EEB6",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      fontFamily: {
        "avenir-next": ["Avenir Next", "sans-serif"],
        "playfair-display": ["Playfair Display", "serif"],
        "space-grotesk": ["Space Grotesk", "sans-serif"],
      },
      boxShadow: {
        "md-glow": "0 4px 10px rgba(217, 72, 15, 0.4)",
        "lg-glow": "0 6px 15px rgba(226, 88, 34, 0.5)",
        center: "0 0 12px -2px rgb(0 0 0 / 0.05)",
      },
      backgroundImage: {
        "hero-pattern": "linear-gradient(to right, #D9480F, #E25822)",
      },
      animation: {
        "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
}
